GET  http://localhost:3000/alumnos

###

GET  http://localhost:3000/alumnos/8

###

POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id":6,
    "nombre":"Mario",
    "Carrera":"Culinario"
}
###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id":7,
    "nombre":"Emiliano",
    "Carrera":"Ingenieria nuclear"
}

###

PUT http://localhost:3000/alumnos/1
Content-Type: application/json

{
    "id":1,
    "nombre":"SartorMateo",
    "carrera":"Loquito del centro"
}

###

DELETE http://localhost:3000/alumnos/12

###

POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id":8,
    "nombre":123,
    "carrera":"Loquito del centro"
}