GET  http://localhost:3000/alumnos

###

GET  http://localhost:3000/alumnos/1004

###

POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "legajo":1006,
    "nombre":"Mario",
    "carrera":"Culinario",
    "correo":"mario@gmail.com"
}
###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "legajo":1006,
    "nombre":"Emiliano",
    "carrera":"Ingenieria nuclear",
    "correo":"emi@gmail.com"
}

###

PUT http://localhost:3000/alumnos/1001
Content-Type: application/json

{
    "legajo":1001,
    "nombre":"SartorMateo",
    "carrera":"Loquito del centro.v2",
    "correo":"mateoresa@gmail.com"
}

###

DELETE http://localhost:3000/alumnos/1006

###

POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id":8,
    "nombre":123,
    "carrera":"Loquito del centro"
}